### ISSUE TITLE
Server became unresponsive. 

### ISSUE THREAD

**Issue by fmjensen** [tom2208/ChestCleaner#33]
I suspect that ChestCleaner might have something to do with it so i thought it be better i post it here. This have never happened until a few hours after i installed ChestCleaner 2.0. I had no other version of ChestCleaner installed before 2.0, and the only other plugin i run is Dynmap. Server is based on Paperclip.jar v. 1.15.2

```
[20:38:16] [Server thread/INFO]: SomeGamer joined the game
[20:38:17] [Server thread/INFO]: SomeGamer [/IP ADDR:53748] logged in with entity id 1 at ([world]114.0849586267286, 63.0, 218.38341590479666)
[20:41:35] [Server thread/INFO]: SomeGamer lost connection: Disconnected
[20:41:35] [Server thread/INFO]: SomeGamer left the game
[20:48:03] [Craft Scheduler Thread - 5/WARN]: java.net.UnknownHostException: api.spigotmc.org
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/java.net.Socket.connect(Socket.java:609)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at chestcleaner.main.UpdateChecker$1.lambda$0(UpdateChecker.java:48)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[20:48:03] [Craft Scheduler Thread - 5/WARN]:   at java.base/java.lang.Thread.run(Thread.java:834)
```

Server reacted fine to commands entered directly into server CLI.

**Comment by fmjensen** [comment]
I just had another incident with this WARN. This time the server did not become unresponsive. Everything seem to work as intended. I do not know why i could not access the server yesterday and cannot replicate the problem any more so I will close this now.
