### ISSUE TITLE
Supporting Paper Spigot

### ISSUE THREAD

**Issue by tom2208** [tom2208/ChestCleaner#9]
https://github.com/PaperMC/Paper

**Comment by 0xBADDCAFE** [comment]
I'm using this plugin in PaperMC. It seems working fine currently.

```
Paper version git-Paper-318 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

Thanks to create awesome plugin.

**Comment by ZachMyers3** [comment]
Adding to this now... it appears to not be working.

I appear to be running the proper spigot API through paper but am getting a fail on loading the plugin.

The API being loaded:
```
This server is running Paper version git-Paper-173 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)
```

The error further down the logs:
```
[09:27:33 ERROR]: Could not load 'plugins/ChestCleaner-2.2.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[patched_1.16.2.jar:git-Paper-173]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.2.jar:git-Paper-173]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:387) ~[patched_1.16.2.jar:git-Paper-173]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.2.jar:git-Paper-173]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-173]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-173]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_212]
        at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_212]
        at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_212]
        at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_212]
        at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.16.2.jar:git-Paper-173]
        ... 6 more
```

If I can provide more information please let me know.

Thanks!

**Comment by tom2208** [comment]
Pretty weird. Paperspigot is making trouble all the time, pretty annoying.

**Comment by ZachMyers3** [comment]
Yeah, I can confirm this was working on spigot but I migrated to paper for the performance gains.

This is the only plugin that didn't make it across the migration, though.

**Comment by tom2208** [comment]
I set up a paper spigot server using the latest server version: [Build 178]( https://papermc.io/downloads).
And it works fine. The server loads properly sorting works fine etc.

> [14:35:37 INFO]: Time elapsed: 3958 ms
> [14:35:37 INFO]: Preparing start region for dimension minecraft:the_nether
> [14:35:37 INFO]: Loaded 0 spawn chunks for world world_nether
> [14:35:37 INFO]: Time elapsed: 189 ms
> [14:35:37 INFO]: Preparing start region for dimension minecraft:the_end
> [14:35:38 INFO]: Loaded 0 spawn chunks for world world_the_end
> [14:35:41 INFO]: Time elapsed: 3848 ms
> [14:35:41 INFO]: [ChestCleaner] Enabling ChestCleaner v2.2.1
> [14:35:42 WARN]: [ChestCleaner] Could not save ChestCleaner_2-2-1_en_GB.properties to plugins\ChestCleaner\ChestCleaner_2-2-1_en_GB.properties because ChestCleaner_2-2-1_en_GB.properties already exists.
> [14:35:42 WARN]: [ChestCleaner] Could not save ChestCleaner_2-2-1_de_DE.properties to plugins\ChestCleaner\ChestCleaner_2-2-1_de_DE.properties because ChestCleaner_2-2-1_de_DE.properties already exists.
> [14:35:44 INFO]: Running delayed init tasks
> [14:35:44 INFO]: Done (13.419s)! For help, type "help"

Try to update your server software.

**Comment by ZachMyers3** [comment]
I wonder if the jar got corrupted in downloading, or just updating to latest was what I needed.

Either way, it works now!

My apologies for wasting your time.

```
[08:45:16 INFO]: [ChestCleaner] Enabling ChestCleaner v2.2.1
```

**Comment by tom2208** [comment]
Ay, was no waste. Im glad i could help.
